# Generated by Django 5.2.1 on 2025-05-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesmodel',
            name='created_at',
        ),
    ]
